python -OO -m PyInstaller main.py ^
	--clean ^
        -D ^
        --name "Degree Planner" ^
        --add-data images/;images ^
        --add-data templates/;templates ^
        --add-data saves/;saves ^
        --add-data db/;db ^
        --add-data setting.json;/ ^
	    -i images/main_icon.ico ^
	    -c ^
        -w
