# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heb_tab.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1064, 541)
        Form.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.semester_average_label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.semester_average_label_2.sizePolicy().hasHeightForWidth())
        self.semester_average_label_2.setSizePolicy(sizePolicy)
        self.semester_average_label_2.setObjectName("semester_average_label_2")
        self.horizontalLayout_7.addWidget(self.semester_average_label_2)
        self.semester_average_in_2 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.semester_average_in_2.sizePolicy().hasHeightForWidth())
        self.semester_average_in_2.setSizePolicy(sizePolicy)
        self.semester_average_in_2.setText("")
        self.semester_average_in_2.setAlignment(QtCore.Qt.AlignCenter)
        self.semester_average_in_2.setReadOnly(True)
        self.semester_average_in_2.setObjectName("semester_average_in_2")
        self.horizontalLayout_7.addWidget(self.semester_average_in_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.semester_points_label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.semester_points_label_2.sizePolicy().hasHeightForWidth())
        self.semester_points_label_2.setSizePolicy(sizePolicy)
        self.semester_points_label_2.setObjectName("semester_points_label_2")
        self.horizontalLayout_8.addWidget(self.semester_points_label_2)
        self.semester_points_in_2 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.semester_points_in_2.sizePolicy().hasHeightForWidth())
        self.semester_points_in_2.setSizePolicy(sizePolicy)
        self.semester_points_in_2.setText("")
        self.semester_points_in_2.setAlignment(QtCore.Qt.AlignCenter)
        self.semester_points_in_2.setReadOnly(True)
        self.semester_points_in_2.setObjectName("semester_points_in_2")
        self.horizontalLayout_8.addWidget(self.semester_points_in_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.semester_table_add_line_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.semester_table_add_line_2.sizePolicy().hasHeightForWidth())
        self.semester_table_add_line_2.setSizePolicy(sizePolicy)
        self.semester_table_add_line_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.semester_table_add_line_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/list-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.semester_table_add_line_2.setIcon(icon)
        self.semester_table_add_line_2.setIconSize(QtCore.QSize(32, 32))
        self.semester_table_add_line_2.setObjectName("semester_table_add_line_2")
        self.horizontalLayout_6.addWidget(self.semester_table_add_line_2)
        self.semester_table_remove_line_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.semester_table_remove_line_2.sizePolicy().hasHeightForWidth())
        self.semester_table_remove_line_2.setSizePolicy(sizePolicy)
        self.semester_table_remove_line_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.semester_table_remove_line_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/list-remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.semester_table_remove_line_2.setIcon(icon1)
        self.semester_table_remove_line_2.setIconSize(QtCore.QSize(32, 32))
        self.semester_table_remove_line_2.setObjectName("semester_table_remove_line_2")
        self.horizontalLayout_6.addWidget(self.semester_table_remove_line_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.courses_table_2 = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.courses_table_2.sizePolicy().hasHeightForWidth())
        self.courses_table_2.setSizePolicy(sizePolicy)
        self.courses_table_2.setMouseTracking(True)
        self.courses_table_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.courses_table_2.setObjectName("courses_table_2")
        self.courses_table_2.setColumnCount(6)
        self.courses_table_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.courses_table_2.setHorizontalHeaderItem(5, item)
        self.courses_table_2.horizontalHeader().setVisible(True)
        self.courses_table_2.horizontalHeader().setCascadingSectionResizes(False)
        self.courses_table_2.horizontalHeader().setSortIndicatorShown(True)
        self.courses_table_2.horizontalHeader().setStretchLastSection(False)
        self.courses_table_2.verticalHeader().setVisible(False)
        self.courses_table_2.verticalHeader().setCascadingSectionResizes(True)
        self.courses_table_2.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.courses_table_2, 0, 0, 1, 1)
        self.semester_add_course_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.semester_add_course_2.setFont(font)
        self.semester_add_course_2.setObjectName("semester_add_course_2")
        self.gridLayout.addWidget(self.semester_add_course_2, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.semester_average_label_2.setText(_translate("Form", "ממוצע:   "))
        self.semester_points_label_2.setText(_translate("Form", "מס\' נק\"ז:"))
        self.semester_table_add_line_2.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">הוסף שורה</span></p></body></html>"))
        self.semester_table_remove_line_2.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">הסר שורה</span></p></body></html>"))
        self.courses_table_2.setSortingEnabled(True)
        item = self.courses_table_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "New Row"))
        item = self.courses_table_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "קטגוריה"))
        item = self.courses_table_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "מספר קורס"))
        item = self.courses_table_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "שם קורס"))
        item = self.courses_table_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "נק\"ז"))
        item = self.courses_table_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "ציון"))
        self.semester_add_course_2.setText(_translate("Form", "חפש קורס"))


